// Contenu de vos recettes — séparé du code de l'application (index.html)
// Modifiez ce fichier pour ajouter/changer les recettes de départ.
//
// Conventions de format (uniformisées) :
//  - Verbes du déroulé toujours à l'infinitif.
//  - Tous les ingrédients d'une composante sont listés avant son déroulé.
//  - Recette à plusieurs composantes : un "part" par composante, et une part
//    "Montage" / "Assemblage" finale quand il y a un assemblage.
//  - Quantités : nombre collé à l'unité en minuscules (g, kg, ml, cl), suivi de "de/d'".
//  - "cuillère(s) à soupe/café" en toutes lettres ; durées en "minutes"/"heures".

export const SEED = [
{title:"Bûche de Noël – Roulé au chocolat", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"Les étapes de montage n'étaient pas explicitées dans la recette d'origine : elles ont été reconstituées ici.", labels:["Noël"],
 parts:[
  {name:"Génoise", ingredients:["5 œufs","125g de sucre","100g de farine"], steps:["Préchauffer le four à 180°C.","Blanchir les 5 jaunes d'œufs avec les 125g de sucre.","Monter les 5 blancs d'œufs en neige.","Incorporer délicatement les blancs montés et les 100g de farine tamisée au mélange jaunes-sucre.","Cuire 8 minutes sur plaque recouverte de papier sulfurisé.","Rouler dans un torchon."]},
  {name:"Ganache", ingredients:["250g de chocolat noir","1/2 gousse de vanille","20cl de crème fleurette"], steps:["Bouillir 15cl de crème avec la 1/2 gousse de vanille grattée.","Verser sur les 250g de chocolat noir coupé en carrés.","Attendre 1 minute puis mélanger et laisser refroidir.","Battre les 5cl de crème restants très froide en chantilly et incorporer délicatement."]},
  {name:"Nappage", ingredients:["50g de chocolat noir","30g de beurre","1 jaune d'œuf"], steps:["Fondre les 50g de chocolat noir avec les 30g de beurre et bien mélanger.","Ajouter le jaune d'œuf en remuant vivement pour éviter qu'il cuise."]},
  {name:"Montage", ingredients:[], steps:["Dérouler la génoise refroidie, l'étaler de ganache et la rouler à nouveau sans le torchon.","Couvrir la bûche de nappage et strier à la fourchette.","Réserver au frais jusqu'au service."]}
 ]},
{title:"Caponata", category:"Plat", difficulty:"", servingsBase:4, servingsUnit:"personnes", prepMin:0, cookMin:0, restMin:0, source:"", notes:"Pour le concentré de tomate, essayez de trouver une marque italienne (Cirio, ou du « strattu » sicilien) pour sauver l'honneur.", labels:[],
 parts:[{name:"", ingredients:["1kg d'aubergines (3 aubergines moyennes)","200g d'oignons rouges (2 gros oignons)","150g de céleri branche","40g de concentré de tomate","80g d'olives vertes dénoyautées (~125g avec noyaux)","30g de câpres","20g de raisins secs sultanines","20g de pignons","30g de vinaigre de vin blanc","30g de sucre en poudre","25g d'huile d'olive","200g d'eau","Sel, poivre noir du moulin","Huile neutre pour les aubergines (si cuisson à la poêle)"],
 steps:["Couper le kilo d'aubergines en tranches épaisses dans la longueur, puis en cubes. Cuire au air fryer.","Saler, poivrer, mélanger, goûter, ajuster.","Torréfier les 20g de pignons à sec dans une poêle et réserver.","Dénoyauter les 80g d'olives vertes et les couper en rondelles.","Couper les 150g de céleri branche en petits morceaux et les faire bouillir jusqu'à ce qu'ils deviennent tendres.","Hacher finement les 200g d'oignons rouges.","Mélanger les 30g de vinaigre de vin blanc avec les 30g de sucre en poudre.","Verser les 25g d'huile d'olive dans une cocotte.","Quand l'huile est chaude, ajouter les oignons et les faire revenir 5 minutes sur feu assez fort en remuant régulièrement. Ils doivent bien colorer sans brûler.","Ajouter le céleri bouilli et mélanger.","Ajouter les 40g de concentré de tomate, mélanger et faire revenir 2 minutes sur feu assez fort.","Ajouter les 30g de câpres, les 80g d'olives et les 20g de raisins secs.","Verser les 200g d'eau.","Couvrir et laisser mijoter 1 heure sur feu très doux.","Éteindre le feu, ajouter les aubergines et les pignons torréfiés."]}]},
{title:"Charlotte au chocolat", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["25 boudoirs ou biscuits cuiller","Environ un bol de liquide pour les imbiber","250g de chocolat","50g de beurre","4 jaunes d'œuf","1 cuillère à soupe de sucre","20cl de crème liquide entière très froide","4 blancs d'œuf","1 pincée de sel"],
 steps:["Tapisser un moule avec les 25 boudoirs imbibés du bol de liquide (café, etc.).","Faire fondre les 250g de chocolat et les 50g de beurre (environ 3 minutes à puissance moyenne au micro-ondes).","Ajouter les 4 jaunes d'œuf.","Battre la cuillère à soupe de sucre et les 20cl de crème liquide entière très froide en chantilly, et l'ajouter à la crème chocolatée.","Battre les 4 blancs d'œuf avec la pincée de sel en neige, et les incorporer à la ganache.","Recouvrir les biscuits et laisser prendre au frigo."]}]},
{title:"Fondant au chocolat", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:15, restMin:0, source:"", notes:"La noix de coco râpée est optionnelle.", labels:[],
 parts:[{name:"", ingredients:["200g de chocolat à cuire","170g de beurre","3 gros ou 4 petits œufs","150g de sucre","Noix de coco râpée (optionnel)","1 grosse pincée de sel","40g de farine"],
 steps:["Faire fondre les 200g de chocolat et les 170g de beurre.","Battre les œufs, les 150g de sucre, la noix de coco et la pincée de sel.","Ajouter le mélange fondu et bien mélanger.","Ajouter les 40g de farine et mélanger juste assez pour qu'il n'y ait pas de grumeau.","Cuire 15 minutes à 180°C dans un petit moule à tarte recouvert de papier sulfurisé."]}]},
{title:"Macarons à la vanille", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:25, restMin:0, source:"", notes:"Recette étalée sur plusieurs jours (J-4 à J). Voir le tableau de proportions pour ajuster le tant pour tant selon le nombre de macarons souhaité.", labels:[],
 parts:[
  {name:"Biscuits", ingredients:["200g de blancs d'œufs","280g d'amandes","480g de sucre glace","Un peu de sucre (pour serrer les blancs)"], steps:["J-4 : séparer les blancs des jaunes et les conserver au réfrigérateur (ou congélateur).","J-2 : hacher les 280g d'amandes et les torréfier 10 minutes au four à 150°C, puis les faire refroidir.","J-2 : mélanger les amandes et les 480g de sucre glace et passer au hachoir (tant pour tant).","J-1, une heure avant : sortir les 200g de blancs d'œufs du réfrigérateur.","J-1 : battre les blancs d'œufs jusqu'à faire apparaître un bec, en ajoutant un peu de sucre quand ça mousse pour des blancs plus fermes.","Ajouter le tant pour tant en deux temps et macaronner (mouvements vigoureux de l'intérieur vers l'extérieur) jusqu'à obtenir le « ruban ».","Préchauffer le four à 150°C avec la plaque à l'intérieur.","Mettre l'appareil en poche à douille, positionner des boules de 2cm espacées de 3cm sur papier sulfurisé.","Cuire 25 minutes sur la plaque chaude, puis laisser refroidir."]},
  {name:"Ganache", ingredients:["2 gousses de vanille","300g de crème liquide","330g de couverture ivoire (chocolat blanc)"], steps:["J-2 : fendre les 2 gousses de vanille, gratter les grains, mélanger avec les 300g de crème dans une casserole et porter à ébullition. Laisser infuser une demi-heure.","Faire fondre les 330g de chocolat blanc.","Retirer les gousses de vanille de la crème et l'ajouter au chocolat fondu en trois fois, en émulsionnant à la maryse.","Réserver au frais."]},
  {name:"Montage", ingredients:[], steps:["J-1 : garnir une poche à douille de ganache, placer une noix sur la moitié des coques et recouvrir avec les autres. Réfrigérer.","J : sortir les macarons à température ambiante une demi-heure avant dégustation."]}
 ]},
{title:"Pizza libanaise", category:"Plat", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"La recette d'origine ne précisait ni le support (pains libanais ou pâte à pizza), ni l'assemblage, ni la cuisson : ces éléments ont été reconstitués et restent à préciser selon votre habitude.", labels:[],
 parts:[{name:"", ingredients:["1 oignon ou 3 échalotes","200g de bœuf haché","4 tomates crues en petits cubes","1 cuillère à soupe de cannelle","1 cuillère à soupe de mélasse de grenade","1 petite tasse à café de vinaigre de cidre","2 cuillères à soupe de tahin","1 cuillère à soupe de sumac","Des pignons","Du poivre 5 baies","Des pains libanais ou une pâte à pizza"],
 steps:["Faire revenir l'oignon ou les échalotes.","Ajouter les 200g de bœuf haché.","Dans un saladier, mélanger les 4 tomates en petits cubes, la cuillère à soupe de cannelle, la cuillère à soupe de mélasse de grenade, la tasse de vinaigre de cidre, les 2 cuillères à soupe de tahin, la cuillère à soupe de sumac, les pignons et le poivre 5 baies.","Ajouter la viande revenue au saladier et mélanger.","Répartir la garniture sur les pains libanais et enfourner à four chaud jusqu'à coloration."]}]},
{title:"Nougat glacé framboises et fruits secs caramélisés", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[
  {name:"Fruits secs caramélisés", ingredients:["35g de noisettes","35g d'amandes","50g de sucre","5g de beurre","1 pincée de fleur de sel"], steps:["Torréfier les 35g de noisettes et 35g d'amandes 10 à 15 minutes à 160°C chaleur tournante (ou 5 minutes au air fryer). Laisser refroidir puis frotter entre les mains pour retirer la peau des noisettes.","Concasser grossièrement au rouleau à pâtisserie dans un sac congélation.","Dans une poêle, verser les amandes et noisettes avec les 50g de sucre. Remuer sans arrêt sur feu moyen/fort jusqu'à caramel ambré.","Éteindre le feu, ajouter les 5g de beurre et la pincée de fleur de sel, mélanger. Étaler sur papier sulfurisé et laisser refroidir."]},
  {name:"Crème montée", ingredients:["1 brique de 33cl de crème fleurette entière (~310g)"], steps:["Monter la brique de 33cl de crème fleurette au robot, à petite vitesse puis en augmentant progressivement. Réserver au frais."]},
  {name:"Meringue italienne", ingredients:["80g de blancs d'œufs","20g de sucre","35g de sucre","65g de miel","20g de sirop de glucose","1 pincée de sel"], steps:["Dans une casserole, verser les 35g de sucre, les 65g de miel et les 20g de sirop de glucose. Porter à ébullition jusqu'à 120°C (thermomètre).","Dans le robot, verser les 80g de blancs d'œufs, les 20g de sucre et la pincée de sel. Fouetter 20 secondes à vitesse max.","Verser le sirop chaud d'un coup sur les blancs, racler la casserole.","Fouetter à vitesse max pendant 5 minutes jusqu'à ce que la meringue soit bien refroidie."]},
  {name:"Montage et service", ingredients:["35g de pistaches émondées non salées","200g de framboises","200g de coulis de framboise"], steps:["Ajouter les fruits secs caramélisés et les 35g de pistaches à la meringue, mélanger délicatement à la maryse.","Incorporer la crème montée.","Chemiser un moule à cake de film alimentaire, verser la préparation, lisser, recouvrir et congeler une nuit.","Le jour J, démouler en tirant sur le film. Servir immédiatement avec les 200g de coulis et les 200g de framboises, en coupant vite avec un bon couteau."]}
 ]},
{title:"Pounti", category:"Plat", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:60, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["300g de lard ou de chair à saucisse","3 oignons","1 bouquet de persil","Les feuilles d'une blette","15cl de lait","80g de farine","4 œufs","30 pruneaux","Sel, poivre","Beurre pour la terrine"],
 steps:["Faire un hachis avec le bouquet de persil, les feuilles de blette, les 3 oignons et les 300g de lard.","Mélanger avec les 15cl de lait, les 80g de farine et les 4 œufs.","Saler, poivrer.","Beurrer une terrine, tapisser le fond avec la farce, répartir les 30 pruneaux et recouvrir avec le reste de la farce.","Cuire 1 heure à 180°C."]}]},
{title:"Tarte aux fruits secs et au caramel", category:"Dessert", difficulty:"", servingsBase:1, servingsUnit:"tarte", prepMin:0, cookMin:25, restMin:0, source:"", notes:"Attention, les composantes ne sont pas données pour la même quantité. Le curseur est réglé sur 1 tarte, ce qui correspond aux fruits secs. La pâte sucrée et le caramel, eux, sont préparés pour 3 tartes : c'est plus simple à faire en une seule fois, et cela se conserve — les 2 boules de pâte en trop vont au congélateur, le caramel se garde au réfrigérateur (environ 1,5 pot de confiture pour 3 tartes).", labels:[],
 parts:[
  {name:"Pâte sucrée", ingredients:["500g de farine","300g de beurre pommade doux","180g de sucre","60g de poudre d'amande","2 œufs","2g de fleur de sel"], steps:["Crémer les 300g de beurre.","Ajouter les 180g de sucre, les 60g de poudre d'amande, les 2g de fleur de sel et battre au moins 2 minutes.","Ajouter les 2 œufs et battre encore 1 minute.","Verser les 500g de farine et mélanger le moins possible.","Séparer en 3 boules ; en congeler 2, garder la 3ème une nuit au frigo.","Le lendemain, étaler entre deux feuilles de papier sulfurisé, mettre dans le moule à tarte et laisser 30 minutes au frigo.","Cuire 25 minutes à 160°C (à adapter)."]},
  {name:"Caramel", ingredients:["240g de sucre","120g de beurre salé","30cl de crème liquide"], steps:["Chauffer les 240g de sucre à sec sur feu moyen jusqu'à obtenir un caramel ambré (3 à 4 minutes).","Pendant ce temps, faire chauffer les 30cl de crème liquide.","Retirer la casserole du feu, ajouter une petite partie de la crème en faisant attention aux projections, remuer vivement puis incorporer le reste.","Ajouter les 120g de beurre et remuer jusqu'à une crème homogène.","Si trop liquide, remettre sur feu doux et remuer jusqu'à la consistance souhaitée."]},
  {name:"Fruits secs", ingredients:["40g de noix","40g de noisettes","40g d'amandes","40g de cacahuètes grillées et salées","30g de pistaches émondées non salées","20g de pignons de pins"], steps:["Torréfier les 40g de noix, 40g de noisettes, 40g d'amandes, 40g de cacahuètes, 30g de pistaches et 20g de pignons 15 minutes à 150°C."]},
  {name:"Montage", ingredients:[], steps:["Répartir les fruits secs torréfiés sur le fond de tarte cuit et refroidi.","Napper de caramel tiède et laisser prendre à température ambiante."]}
 ]},
{title:"Stollen de Noël", category:"Boulangerie", difficulty:"", servingsBase:1, servingsUnit:"stollen", prepMin:0, cookMin:40, restMin:0, source:"", notes:"Attention, les composantes ne sont pas données pour la même quantité. Le curseur est réglé sur 1 stollen, ce qui correspond au levain, à la pâte à brioche et à la garniture. La pâte d'amande, elle, est préparée en plus grande quantité alors qu'on n'en utilise que 80 à 100g : c'est plus simple à faire en une seule fois, et elle se conserve environ 1 mois au réfrigérateur.", labels:["Noël"],
 parts:[
  {name:"Pâte d'amande", ingredients:["250g d'amandes en poudre","210g de sucre","1 à 2 blancs d'œufs","Quelques gouttes d'extrait d'amande amère"], steps:["Sécher les 250g d'amandes 10 minutes à 150°C sur plaque, laisser refroidir.","Mixer les amandes et les 210g de sucre.","Ajouter un blanc d'œuf et quelques gouttes d'extrait d'amande amère, travailler rapidement la pâte (ajuster avec blanc d'œuf ou amandes en poudre selon la texture).","Former un boudin, filmer, conserver au frigo."]},
  {name:"Levain", ingredients:["150g de lait","25g de levure de boulanger fraîche (ou 8g déshydratée)","200g de farine"], steps:["Mélanger les 25g de levure, les 150g de lait et les 200g de farine dans un récipient.","Couvrir d'un torchon et laisser reposer 1 heure à température ambiante, jusqu'à ce qu'il double de volume."]},
  {name:"Pâte à brioche", ingredients:["200g de farine","25g de sucre","170g de beurre mou","2 pincées de cannelle","1 cuillère à café de sel"], steps:["Ajouter au levain poussé les 200g de farine, les 25g de sucre, les 2 pincées de cannelle, la cuillère à café de sel et les 170g de beurre mou.","Mélanger jusqu'à une pâte homogène et pétrir quelques minutes.","Prélever 1/5 de la pâte et réserver au frigo dans du film alimentaire."]},
  {name:"Garniture et cuisson", ingredients:["80 à 100g de pâte d'amande","50g d'amandes entières","50g de noisettes entières","80g de raisins secs","Un peu d'eau","Un peu de farine pour le plan de travail"], steps:["Mélanger les 4/5 de pâte restants avec les 50g d'amandes et 50g de noisettes hachées grossièrement et les 80g de raisins.","Laisser pousser 30 minutes à température ambiante, retravailler, former un boudin, laisser reposer 30 minutes.","Fariner le plan de travail, étaler le morceau de pâte réservé sur 3mm en rectangle.","Badigeonner d'un peu d'eau et envelopper le boudin avec les 80 à 100g de pâte d'amande dedans. Laisser reposer 20 à 30 minutes.","Préchauffer le four à 180°C.","Cuire 40 minutes à 180°C."]}
 ]},
{title:"Cookies", category:"Boulangerie", difficulty:"", servingsBase:36, servingsUnit:"cookies", prepMin:0, cookMin:0, restMin:0, source:"", notes:"Attention, certaines quantités sont exprimées en volume.", labels:[],
 parts:[{name:"", ingredients:["560ml (360g) de farine","1 cuillère à café de sel","1 cuillère à café de levure","180ml (160g) de sucre roux","1 cuillère à soupe de vanille liquide","170g de beurre","2 œufs","100g de chocolat noir"],
 steps:["Casser les 100g de chocolat pour en faire des pépites.","Dans un petit bol, mélanger les 360g de farine, la cuillère à café de sel, la cuillère à café de levure et le chocolat en pépites.","Dans un grand bol, faire une pommade avec les 170g de beurre, ajouter les 160g de sucre roux puis les 2 œufs et la cuillère à soupe de vanille liquide. Bien battre.","Verser le contenu du petit bol dans le grand bol et mélanger rapidement (s'arrêter dès qu'on ne distingue plus la farine).","Préchauffer le four à 190°C.","Placer 12 tas de pâte sur 3 plaques recouvertes de papier sulfurisé.","Cuire séparément chaque plaque 6 à 10 minutes : le bord doit être coloré, le milieu encore tendre."]}]},
{title:"Cheesecake", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:50, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["24 biscuits Thé","80g de beurre","600g de Philadelphia cream cheese","6 petits suisses","100g de sucre","4 œufs","1 cuillère à soupe de vanille liquide"],
 steps:["Broyer les 24 biscuits Thé.","Faire fondre les 80g de beurre, le verser sur les biscuits et mélanger.","Verser dans un moule recouvert de papier sulfurisé, tasser au dos d'une cuillère, réserver au réfrigérateur.","Préchauffer le four à 150°C.","Fouetter les 600g de Philadelphia et les 6 petits suisses, ajouter les 100g de sucre, les 4 œufs et la cuillère à soupe de vanille, mélanger.","Verser sur les biscuits écrasés et enfourner 50 minutes (la crème doit trembloter légèrement à la sortie du four)."]}]},
{title:"Carrot cake", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:25, restMin:0, source:"", notes:"", labels:[],
 parts:[
  {name:"Biscuit", ingredients:["180g de farine","1 cuillère à café de levure","1 pincée de cannelle","1/2 cuillère à café de sel","90g d'huile","120g de sucre roux","2 œufs","1 cuillère à café de vanille liquide","3 carottes râpées","60g de noix concassées"], steps:["Battre ensemble les 180g de farine, la cuillère à café de levure, la pincée de cannelle, la 1/2 cuillère à café de sel, les 90g d'huile, les 120g de sucre roux, les 2 œufs, la cuillère à café de vanille, les 3 carottes râpées et les 60g de noix concassées, puis verser dans un moule rond.","Cuire 10 minutes à 200°C puis 15 minutes à 180°C."]},
  {name:"Nappage", ingredients:["50g de beurre mou","100g de sucre glace","1 cuillère à soupe de vanille liquide","300g de Philadelphia cream cheese"], steps:["Battre les 50g de beurre en pommade, intégrer les 100g de sucre glace puis la cuillère à soupe de vanille, puis les 300g de Philadelphia.","Napper le biscuit lorsqu'il est bien refroidi."]}
 ]},
{title:"Tarte aux noix et au chocolat", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:45, restMin:0, source:"", notes:"", labels:[],
 parts:[
  {name:"Pâte sablée", ingredients:["250g de farine","100g de beurre à température ambiante","1 petit verre d'eau","1 grosse pincée de sel","1 cuillère à soupe de sucre"], steps:["Mélanger les 250g de farine, la pincée de sel et la cuillère à soupe de sucre.","Ajouter les 100g de beurre et sabler.","Ajouter le petit verre d'eau et pétrir jusqu'à former une boule, sans insister.","Laisser reposer à température ambiante."]},
  {name:"Appareil aux noix", ingredients:["250g de cerneaux de noix","150g de sucre en poudre","3 œufs entiers","25cl de crème liquide entière"], steps:["Hacher les 250g de noix.","Battre avec les 150g de sucre, les 3 œufs entiers et les 25cl de crème."]},
  {name:"Montage et nappage", ingredients:["125g de chocolat noir à pâtisser","50g de beurre"], steps:["Préchauffer le four à 180°C.","Étaler la pâte, verser l'appareil aux noix dessus dans la tourtière.","Cuire 45 minutes.","Faire fondre les 125g de chocolat avec les 50g de beurre au micro-ondes à puissance moyenne, émulsionner et verser sur la tarte encore chaude."]}
 ]},
{title:"Muffins anglais", category:"Boulangerie", difficulty:"", servingsBase:12, servingsUnit:"muffins", prepMin:0, cookMin:14, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["500g de farine","1 cuillère à soupe de sucre","30cl de lait","1 sachet de levure de boulanger"],
 steps:["Faire tiédir les 30cl de lait, y ajouter la cuillère à soupe de sucre et le sachet de levure, laisser reposer.","Verser sur les 500g de farine et pétrir 10 minutes.","Laisser reposer 1 heure.","Étaler au rouleau sur 1cm d'épaisseur, découper des ronds à l'emporte-pièce.","Laisser reposer 1 heure.","Cuire à la poêle 7 minutes de chaque côté, sur feu moyen, sans matière grasse."]}]},
{title:"Banana bread", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:45, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["300g de farine","1 cuillère à café de levure chimique","1/2 cuillère à café de sel","1 pincée de cannelle","80g de cassonade","50g de beurre fondu","3 œufs","3 à 5 bananes mûres réduites en purée","2 yaourts","1 cuillère à café d'extrait de vanille","60g de chocolat en pépites"],
 steps:["Préchauffer le four à 180°C.","Mélanger les 300g de farine, la cuillère à café de levure, la 1/2 cuillère à café de sel, la pincée de cannelle et les 80g de cassonade.","Dans un autre bol, mélanger les 50g de beurre fondu, les 3 œufs, les bananes réduites en purée, les 2 yaourts et la cuillère à café de vanille.","Creuser un puits dans les ingrédients secs et y verser les liquides.","Mélanger grossièrement, ajouter les 60g de pépites de chocolat, mélanger à nouveau sans trop insister.","Verser dans le moule.","Enfourner environ 45 minutes, jusqu'à ce que le cake soit tout juste cuit."]}]},
{title:"Scones", category:"Boulangerie", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["350g de farine","1/4 de cuillère à café de sel","1 sachet de levure chimique","85g de beurre mou en petits cubes","2 cuillères à soupe de sucre","115ml de lait fermenté (ou lait additionné de jus de citron)","1 gousse de vanille","Un peu de farine pour le plan de travail"],
 steps:["Préchauffer le four à 220°C avec la plaque à l'intérieur.","Faire tiédir les 115ml de lait fermenté et la gousse de vanille dans une casserole.","Mélanger les 350g de farine, le sachet de levure, le 1/4 de cuillère à café de sel et les 2 cuillères à soupe de sucre. Ajouter les 85g de beurre et pétrir jusqu'à consistance sableuse.","Ajouter le mélange tiède et mélanger brièvement au couteau.","Fariner le plan de travail, replier la pâte plusieurs fois sur elle-même, étaler sur 3,5 à 4cm d'épaisseur.","Couper des ronds de 5cm de diamètre.","Cuire 12 à 14 minutes."]}]},
{title:"Brioche-dog", category:"Plat", difficulty:"", servingsBase:5, servingsUnit:"brioches", prepMin:0, cookMin:30, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["300g de farine","175ml de lait","20g de beurre","1 sachet de levure boulangère sèche","1 cuillère à soupe de sucre","1 cuillère à café de sel","1 œuf battu (moitié pour la pâte, moitié pour la dorure)","5 knacks","2 gros oignons","Du comté"],
 steps:["Faire revenir les 2 oignons.","Faire tiédir au micro-ondes les 175ml de lait et les 20g de beurre, y ajouter la cuillère à soupe de sucre et le sachet de levure, laisser gonfler quelques minutes.","Verser les 300g de farine et la cuillère à café de sel dans un saladier, ajouter la levure gonflée puis la moitié de l'œuf battu et pétrir 10 minutes.","Étaler la pâte au rouleau, découper 5 rectangles.","Déposer de l'oignon, du comté et une knack sur chaque rectangle et façonner des sandwichs. Laisser gonfler 1 heure.","Préchauffer le four à 200°C.","Recouvrir les sandwichs de comté, les badigeonner avec le reste de l'œuf battu et enfourner 30 minutes."]}]},
{title:"Baba au rhum", category:"Dessert", difficulty:"", servingsBase:1, servingsUnit:"gros baba", prepMin:0, cookMin:20, restMin:0, source:"", notes:"On peut ajouter des fraises pour un goût plus savoureux.", labels:[],
 parts:[
  {name:"Pâte à baba", ingredients:["180g de farine","20g de sucre semoule","4g de sel","10g de levure boulangère","8g de lait","2 œufs de taille moyenne","60g de beurre doux","Beurre pour le moule"], steps:["Pétrir les 180g de farine, les 20g de sucre et les 4g de sel.","Délayer les 10g de levure avec les 8g de lait, l'ajouter au mélange et pétrir.","Fouetter les 2 œufs et les incorporer. Pétrir jusqu'à ce que la pâte se décolle des parois de la cuve.","Incorporer les 60g de beurre en pommade en trois fois, pétrir jusqu'à obtenir un appareil élastique.","Laisser pousser 45 minutes dans une pièce chaude.","Beurrer le moule à baba et dresser la pâte aux deux tiers du moule. Laisser pousser à nouveau 30 minutes.","Préchauffer le four à 180°C, puis enfourner pour 20 minutes."]},
  {name:"Sirop", ingredients:["230g de sucre semoule","520g d'eau","1 gousse de vanille","120g de rhum"], steps:["Porter à ébullition les 520g d'eau et les 230g de sucre dans une casserole.","Ajouter la gousse de vanille fendue et grattée, incorporer les 120g de rhum.","Couvrir et laisser infuser 30 minutes à feu doux. Réserver au chaud."]},
  {name:"Crème Chantilly vanille", ingredients:["300g de crème liquide","1 gousse de vanille","20g de sucre glace"], steps:["Monter les 300g de crème liquide bien froide au batteur.","Une fois montée, incorporer les graines de la gousse de vanille et serrer avec les 20g de sucre glace. Réserver au frais."]},
  {name:"Montage", ingredients:[], steps:["Tremper le baba dans le sirop chaud puis l'égoutter.","Une fois refroidi, garnir le centre de crème chantilly vanille."]}
 ],
 schemaGraph:{ nodes:[
   {id:"n1", label:"Pétrir", inputs:["ing:0","ing:1","ing:2"]},
   {id:"n2", label:"Délayer", inputs:["ing:3","ing:4"]},
   {id:"n3", label:"Fouetter", inputs:["ing:5"]},
   {id:"n4", label:"Battre en pommade", inputs:["ing:6"]},
   {id:"n5", label:"Mélanger", inputs:["n1","n2"]},
   {id:"n6", label:"Mélanger", inputs:["n5","n3"]},
   {id:"n7", label:"Pétrir et laisser pousser 45 minutes dans une pièce chaude", inputs:["n6","n4"]},
   {id:"n8", label:"Préchauffer le four à 180°C et cuire 20 minutes", inputs:["n7","ing:7"]},
   {id:"s1", label:"Porter à ébullition", inputs:["ing:9","ing:8"]},
   {id:"s2", label:"Ajouter la vanille et incorporer le rhum", inputs:["s1","ing:10","ing:11"]},
   {id:"s3", label:"Laisser infuser 30 minutes", inputs:["s2"]},
   {id:"s4", label:"Tremper le baba puis égoutter", inputs:["s3","n8"]},
   {id:"c1", label:"Monter", inputs:["ing:12"]},
   {id:"c2", label:"Incorporer la vanille et le sucre glace", inputs:["c1","ing:13","ing:14"]},
   {id:"f1", label:"Garnir le centre de crème chantilly", inputs:["s4","c2"]}
 ]}},
{title:"Riz au lait indien", category:"Dessert", difficulty:"", servingsBase:6, servingsUnit:"personnes", prepMin:0, cookMin:0, restMin:0, source:"", notes:"La recette est très bonne même sans pistaches si vous n'en trouvez pas.", labels:[],
 parts:[{name:"", ingredients:["100g de riz thaï (ou basmati)","60cl de lait","4 cuillères à soupe de sucre","4 gousses de cardamome verte","1 cuillère à soupe d'amandes effilées","1 cuillère à soupe de pistaches non salées écrasées","1 dose de safran"],
 steps:["Mettre les 60cl de lait, les 4 gousses de cardamome écrasées et les 100g de riz dans une casserole, porter à ébullition.","Faire cuire à petits bouillons jusqu'à ce que le riz soit très cuit (les grains commencent à se défaire).","Ajouter la cuillère à soupe d'amandes effilées et la cuillère à soupe de pistaches, cuire encore quelques minutes.","Ajouter les 4 cuillères à soupe de sucre et la dose de safran à la fin et diluer en tournant.","Servir tiède ou frais."]}]},
{title:"Roulé aux courgettes et au saumon", category:"Entrée", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:25, restMin:60, source:"", notes:"", labels:[],
 parts:[
  {name:"Biscuit aux courgettes", ingredients:["3 courgettes râpées","1 filet d'huile d'olive","3 œufs","2 cuillères à soupe de crème fraîche épaisse","50g de farine","Sel, poivre"], steps:["Râper les 3 courgettes, les faire revenir dans le filet d'huile d'olive pour leur faire rendre leur eau. Réserver.","Séparer les blancs des jaunes des 3 œufs. Battre les jaunes avec les 2 cuillères à soupe de crème fraîche et les 50g de farine.","Incorporer délicatement les blancs battus en neige.","Ajouter les courgettes râpées. Saler, poivrer et rectifier l'assaisonnement.","Verser dans un plat à roulé. Cuire environ 25 minutes au four."]},
  {name:"Garniture et montage", ingredients:["Une petite boite (125g) de Philadelphia","1 bouquet de ciboulette","8 tranches de saumon fumé"], steps:["Démouler le biscuit, étaler les 125g de Philadelphia mélangés au bouquet de ciboulette sur le roulé, disposer les 8 tranches de saumon.","Rouler le gâteau en serrant bien, filmer et laisser 1 heure au réfrigérateur minimum."]}
 ]},
{title:"Tarte au citron", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:30, restMin:0, source:"", notes:"", labels:[],
 parts:[
  {name:"Pâte sablée", ingredients:["250g de farine","100g de beurre à température ambiante","1 petit verre d'eau","1 grosse pincée de sel","1 cuillère à soupe de sucre"], steps:["Mélanger les 250g de farine, la pincée de sel et la cuillère à soupe de sucre.","Ajouter les 100g de beurre et sabler.","Ajouter le petit verre d'eau et pétrir jusqu'à former une boule, sans insister.","Laisser reposer à température ambiante, étaler.","Cuire 30 minutes à 180°C."]},
  {name:"Lemon curd", ingredients:["Le zeste et le jus de 2 citrons jaunes","Le zeste et le jus de 1 citron vert","3 œufs","60g de beurre pommade","120g de sucre"], steps:["Mélanger bien le zeste et le jus des 2 citrons jaunes et du citron vert, les 3 œufs, les 60g de beurre pommade et les 120g de sucre dans un cul de poule.","Cuire au bain-marie sans cesser de fouetter, arrêter au premier bouillon.","Tremper le fond du cul de poule dans de l'eau glacée pour stopper la cuisson."]},
  {name:"Montage", ingredients:[], steps:["Verser le lemon curd refroidi sur le fond de tarte refroidi."]}
 ]},
{title:"Tiramisu", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:240, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["Une boite de boudoirs","Un bol de café fort","4 œufs","75g de sucre","1 boite de mascarpone","1 pincée de sel","Du cacao Van Houten"],
 steps:["Imbiber les boudoirs du bol de café fort et les disposer dans un plat.","Battre les 4 jaunes d'œuf avec les 75g de sucre puis incorporer la boite de mascarpone.","Battre les 4 blancs en neige avec la pincée de sel, les incorporer au mélange précédent et recouvrir les biscuits.","Faire prendre au frigo pendant 4 heures.","Saupoudrer de cacao Van Houten avant de servir."]}]},
{title:"Bourriols", category:"Boulangerie", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["20g de levure de boulanger","1 verre d'eau tiède","4 pommes de terre moyennes","3 tasses de farine de froment","1 tasse de farine de blé noir","1 cuillère à café de sel","Du lait"],
 steps:["Laisser lever les 20g de levure de boulanger 10 minutes dans le verre d'eau tiède.","Faire une purée avec les 4 pommes de terre, l'ajouter au levain.","Mélanger les 3 tasses de farine de froment, la tasse de farine de blé noir et la cuillère à café de sel. Ajouter à la purée. Ajouter du lait, mais en gardant une pâte épaisse.","Laisser lever une nuit. Rajouter du lait jusqu'à ce que le mélange soit liquide (mais plus épais que la pâte à crêpes)."]}]},
{title:"Bredele lunes à la noisette", category:"Boulangerie", difficulty:"", servingsBase:40, servingsUnit:"demi-lunes", prepMin:0, cookMin:15, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["120g de noisettes","250g de farine","175g de beurre","100g de sucre"],
 steps:["Hacher les 120g de noisettes en poudre.","Battre les 175g de beurre en pommade.","Mélanger avec les 100g de sucre et les noisettes.","Ajouter les 250g de farine et mélanger juste assez pour obtenir une pâte homogène.","Laisser reposer.","Préchauffer le four à 175°C.","Façonner 40 demi-lunes.","Cuire 15 minutes sur une plaque."]}]},
{title:"Bredele vanille kipferl", category:"Boulangerie", difficulty:"", servingsBase:80, servingsUnit:"cubes", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["70g de sucre","1 gousse de vanille","240g de beurre","280g de farine","120g d'amandes","1 cuillère à café de vanille liquide"],
 steps:["Hacher la gousse de vanille avec les 70g de sucre.","Ajouter les 120g d'amandes et les réduire en poudre.","Battre les 240g de beurre en pommade.","Mélanger tous les ingrédients (y compris la cuillère à café de vanille liquide) sauf la farine.","Ajouter les 280g de farine et mélanger juste assez pour obtenir une pâte homogène.","Laisser reposer.","Préchauffer le four à 170°C.","Façonner 80 cubes de 1,5cm de côté.","Cuire entre 13 et 15 minutes sur une plaque."]}]},
{title:"Bredele bouchées aux noix et au chocolat", category:"Boulangerie", difficulty:"", servingsBase:100, servingsUnit:"bouchées", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["200g de sucre","200g de beurre","2 cuillères à soupe de lait","2 œufs","450g de farine","2 cuillères à café de levure chimique","200g de noix","200g de chocolat"],
 steps:["Hacher grossièrement les 200g de noix.","Couper les 200g de chocolat en pépites.","Battre les 200g de beurre en pommade avec les 200g de sucre.","Ajouter les 2 œufs et les 2 cuillères à soupe de lait.","Ajouter les 450g de farine, les 2 cuillères à café de levure chimique, les noix et le chocolat et mélanger juste assez pour obtenir une pâte homogène.","Laisser reposer.","Préchauffer le four à 200°C.","Façonner 100 bouchées.","Cuire 10 ou 11 minutes sur une plaque."]}]},
{title:"Cake aux noisettes", category:"Dessert", difficulty:"", servingsBase:1, servingsUnit:"cake", prepMin:0, cookMin:60, restMin:0, source:"", notes:"Attention, les composantes ne sont pas données pour la même quantité. Le curseur est réglé sur 1 cake (environ 10 personnes), ce qui correspond aux noisettes caramélisées, à l'appareil à cake et à la ganache. La pâte de noisettes, elle, est préparée en plus grande quantité alors qu'on n'en utilise que 90g en tout (10g dans l'appareil, 80g dans la ganache) : c'est plus simple à faire en une seule fois, et le reste se conserve au frais.", labels:[],
 parts:[
  {name:"Pâte de noisettes", ingredients:["500g de noisettes","5g de fleur de sel"], steps:["Étaler les 500g de noisettes sur une plaque à pâtisserie et les torréfier 12 minutes à 170°C.","Laisser refroidir.","Mixer avec les 5g de fleur de sel jusqu'à obtention d'une pâte."]},
  {name:"Noisettes caramélisées", ingredients:["150g de noisettes","90g d'eau","180g de sucre blanc"], steps:["Porter les 90g d'eau et les 180g de sucre à ébullition. Ajouter les 150g de noisettes et les laisser s'imbiber pendant 30 minutes (garder le sirop pour de prochaines préparations).","Préchauffer le four à 190°C.","Égoutter les noisettes, les étaler sur une plaque recouverte d'un tapis en silicone et mettre au four pendant 12 minutes."]},
  {name:"Appareil à cake", ingredients:["85g de beurre","120g de crème liquide à 18% de matière grasse","1 œuf","150g de sucre","2g de sel","10g de pâte de noisettes","110g de farine T45","5g de levure chimique","30g de poudre ou de brisures de noisettes"], steps:["Préchauffer le four à 145°C.","Faire fondre les 85g de beurre jusqu'à ce qu'il prenne une couleur noisette puis le filtrer.","Battre l'œuf avec les 150g de sucre et les 2g de sel. Ajouter les 10g de pâte de noisettes, les 110g de farine, les 5g de levure et les 30g de poudre de noisettes et mélanger. Ajouter le beurre fondu et les 120g de crème et mélanger.","Faire cuire pendant 1 heure."]},
  {name:"Ganache", ingredients:["150g de chocolat noir","40g de crème liquide à 55% de matière grasse","80g de pâte de noisettes","1g de fleur de sel","25g de beurre"], steps:["Faire bouillir les 40g de crème et la verser sur les 150g de chocolat coupé en morceaux et les 25g de beurre. Faire une émulsion à la maryse, ajouter les 80g de pâte de noisettes et le gramme de fleur de sel."]},
  {name:"Assemblage", ingredients:[], steps:["Démouler le cake, y répartir les noisettes caramélisées et recouvrir de ganache. Faire prendre au réfrigérateur."]}
 ]},
{title:"Cookies au chocolat blanc et aux pistaches", category:"Boulangerie", difficulty:"", servingsBase:24, servingsUnit:"cookies", prepMin:0, cookMin:10, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["150g de beurre","150g de sucre","2 œufs","360g de farine","100g de chocolat blanc","50g de pistaches","1 cuillère à café de levure","De la vanille liquide"],
 steps:["Battre les 150g de beurre en pommade.","Ajouter les 150g de sucre.","Ajouter les 2 œufs.","Couper les 100g de chocolat blanc en pépites et hacher très grossièrement les 50g de pistaches.","Ajouter les 360g de farine, la cuillère à café de levure, la vanille liquide, les pépites et les pistaches et mélanger brièvement, simplement pour obtenir une pâte homogène.","Préchauffer le four à 190°C.","Former 24 boules.","Cuire sur une plaque pendant 10 minutes."]}]},
{title:"Gâteau à la noix de coco", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:30, restMin:0, source:"", notes:"", labels:[],
 parts:[
  {name:"Biscuit", ingredients:["6 jaunes d'œufs","250g de crème à 15% de matière grasse","300g de beurre","350g de farine","300g de sucre","3 cuillères à soupe de cacao","1 cuillère à soupe rase de levure"], steps:["Mélanger les 300g de beurre, les 300g de sucre et les 6 jaunes jusqu'à obtention d'une mousse onctueuse. Ajouter les 250g de crème, les 3 cuillères à soupe de cacao, les 350g de farine et la cuillère à soupe rase de levure : la pâte doit être épaisse et homogène.","Mettre au four à 210°C, cuire 30 minutes à mi-hauteur. Laisser refroidir sur une grille."]},
  {name:"Garniture", ingredients:["300g de crème fraîche liquide","4 blancs d'œufs","1 pincée de sel","100g de noix de coco","2 cuillères à soupe de sucre glace","3 à 4 cuillères à café de cacao","2 cuillères à café de café instantané"], steps:["Fouetter les 300g de crème fraîche liquide. Monter les 4 blancs d'œufs avec la pincée de sel et les 2 cuillères à soupe de sucre glace, ajouter les 100g de noix de coco. Mélanger délicatement la chantilly et les blancs en neige.","Étaler sur le biscuit froid. Saupoudrer des 2 cuillères à café de café instantané et des 3 à 4 cuillères à café de cacao."]}
 ]},
{title:"Gâteau aux framboises", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[
  {name:"Biscuit", ingredients:["20g de beurre","100g de sucre","100g de chocolat à cuire","De la chapelure","4 œufs","150g de noisettes en poudre","100g de farine","3 cuillères à soupe de cacao en poudre","2 cuillères à café de levure"], steps:["Travailler les 20g de beurre en pommade avec les 100g de sucre. Incorporer les jaunes des 4 œufs. Faire fondre les 100g de chocolat.","Préchauffer le four à 180°C. Beurrer un moule de 26cm, le saupoudrer de chapelure.","Amalgamer le chocolat fondu et les 150g de noisettes en poudre à la pâte.","Mélanger les 100g de farine, les 3 cuillères à soupe de cacao et les 2 cuillères à café de levure avant de les incorporer à la pâte.","Monter les blancs en neige. Les ajouter délicatement au mélange.","Cuire 30 à 35 minutes. Laisser reposer 4 à 6 heures."]},
  {name:"Garniture", ingredients:["5 cuillères à soupe de coulis ou de sirop de framboises","500g de framboises","1 cuillère à soupe de sucre vanillé","200g de crème fraîche liquide","3 cuillères à soupe de sucre glace"], steps:["Couper le quart supérieur du biscuit, le réduire en miettes.","Imbiber la couche inférieure avec les 5 cuillères à soupe de coulis, dresser les 500g de framboises dessus.","Fouetter les 200g de crème fraîche liquide avec la cuillère à soupe de sucre vanillé. Recouvrir les framboises. Répandre les miettes de gâteau et saupoudrer des 3 cuillères à soupe de sucre glace."]}
 ]},
{title:"Gâteau aux pommes", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:30, restMin:0, source:"", notes:"La recette d'origine ne donnait aucun déroulé pour la pâte et presque rien pour la garniture : les étapes ci-dessous ont été reconstituées à partir des ingrédients et restent à valider selon votre pratique habituelle des gâteaux pomme/fromage blanc.", labels:[],
 parts:[
  {name:"Pâte", ingredients:["150g de beurre","250g de farine","80g d'amandes en poudre","100g de sucre"], steps:["Mélanger les 250g de farine, les 80g d'amandes en poudre et les 100g de sucre.","Ajouter les 150g de beurre en morceaux et sabler du bout des doigts jusqu'à obtenir une pâte homogène.","Former une boule et laisser reposer au frais.","Étaler la pâte et en foncer un moule."]},
  {name:"Garniture", ingredients:["1kg de pommes","2 jaunes d'œuf","250g de fromage blanc maigre","50g de sucre","1 écorce de cannelle"], steps:["Éplucher le kilo de pommes et les couper en lamelles.","Mélanger les 250g de fromage blanc, les 2 jaunes d'œuf, les 50g de sucre et l'écorce de cannelle.","Répartir les pommes sur la pâte et recouvrir de l'appareil au fromage blanc.","Cuire 30 minutes à 200°C."]}
 ]},
{title:"Kanelbullar", category:"Boulangerie", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:12, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["150g de beurre","300g de lait","20g de levure de boulanger fraîche","700g de farine","1/2 cuillère à café de sel","1 œuf","Du sucre (pour délayer la levure et pour saupoudrer)","De la cannelle en poudre"],
 steps:["Faire fondre 100g de beurre (sur les 150g) et tiédir les 300g de lait.","Délayer les 20g de levure de boulanger dans un peu de sucre.","Mélanger les 700g de farine, la 1/2 cuillère à café de sel puis le mélange levure-sucre.","Ajouter le mélange lait-beurre.","Pétrir 5 minutes.","Ajouter l'œuf et pétrir encore 10 minutes.","Laisser reposer 30 minutes.","Étaler en un rectangle de 30x40cm.","Badigeonner avec les 50g de beurre restants, ramolli.","Saupoudrer de sucre et de cannelle en poudre.","Rouler dans le sens de la longueur.","Couper des anneaux d'environ 3cm de large.","Placer dans un moule rectangulaire et laisser lever 1 heure.","Préchauffer le four à 240°C.","Enfourner et baisser la température à 200°C.","Cuire pendant 12 minutes."]}]},
{title:"Kougelhopf", category:"Boulangerie", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:60, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["50cl de lait","125g de beurre","100g de sucre","3 cuillères à soupe de sucre (pour la levure)","1/2 cuillère à café de sel","27g de levure de boulanger fraîche","1kg de farine","2 œufs","Des amandes","Des raisins blonds","Beurre pour le moule"],
 steps:["Faire tiédir les 50cl de lait, les 125g de beurre, les 100g de sucre et la 1/2 cuillère à café de sel.","Mélanger les 27g de levure et les 3 cuillères à soupe de sucre.","Dans le grand bol du robot, mélanger 750g de farine, le mélange tiède, les 2 œufs et le mélange levure-sucre puis pétrir 5 minutes.","Ajouter les 250g de farine restants et pétrir 10 minutes.","Laisser lever jusqu'à doublement du volume.","Dégazer et ajouter les amandes et les raisins blonds.","Bien beurrer le moule, placer des amandes dans les alcôves, recouvrir de la pâte à brioche et placer au réfrigérateur pour une nuit.","Préchauffer le four à 150°C.","Cuire 15 minutes puis augmenter la température du four à 180°C et poursuivre la cuisson pendant 45 minutes."]}]},
{title:"Kouign amann", category:"Boulangerie", difficulty:"", servingsBase:2, servingsUnit:"kouign amann", prepMin:0, cookMin:25, restMin:0, source:"", notes:"Le beurre et le sucre sont donnés pour les 2 kouign amann, soit 150g de chacun par kouign.", labels:[],
 parts:[{name:"", ingredients:["30cl d'eau","25g de levure","450g de farine","9g de sel","300g de beurre (150g par kouign amann)","300g de sucre (150g par kouign amann)"],
 steps:["Préparer le levain en mélangeant les 25g de levure, 5cl d'eau et une cuillère à soupe de farine (prélevée sur les 450g).","Laisser prendre 10 minutes.","Mélanger le levain, 25cl d'eau, le reste de la farine et les 9g de sel : la pâte doit être homogène (elle reste collante).","Laisser lever la pâte 1 heure 30 sous un torchon. Puis réserver 1 heure au frigo. Partager la pâte en 2.","Sur un torchon fariné ou du papier sulfurisé, étaler au rouleau la pâte en un rond de 30cm environ.","Aplatir 150g de beurre avec la paume de la main (sur le papier beurre).","Décoller cette « galette » de beurre pour la déposer sur la pâte étalée.","Verser 150g de sucre dessus. Rabattre les côtés sur le beurre sucré.","Étaler doucement après avoir fariné dessus et dessous, pour obtenir un rectangle.","Plier en trois (rabattre un côté puis l'autre par-dessus) et tourner d'un quart de tour.","Renouveler l'opération : étaler, plier, tourner. Étaler à nouveau, en carré plutôt. Plier en 2.","Poser le kouign sur un plat beurré ou du papier sulfurisé et cuire 25 minutes à 190°C.","Renouveler l'opération pour le deuxième kouign amann (avec les 150g de beurre et 150g de sucre restants)."]}]},
{title:"Langhopf", category:"Boulangerie", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:37, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["25cl de lait","65g de beurre","50g de sucre","2 cuillères à soupe de sucre (pour la levure)","1/2 cuillère à café de sel","14g de levure de boulanger fraîche","500g de farine","1 œuf","50g de noix","50g d'amandes","50g de noisettes","100g de raisins blonds","Du sucre et de la cannelle pour le glaçage","Un morceau de beurre pour le glaçage","Beurre pour le moule"],
 steps:["Faire tiédir les 25cl de lait, les 65g de beurre, les 50g de sucre et la 1/2 cuillère à café de sel.","Mélanger les 14g de levure et les 2 cuillères à soupe de sucre.","Dans le grand bol du robot, mélanger 400g de farine, le mélange tiède, l'œuf et le mélange levure-sucre puis pétrir 5 minutes.","Ajouter les 100g de farine restants et pétrir 10 minutes.","Laisser lever jusqu'à doublement du volume.","Hacher les 50g de noix, 50g d'amandes et 50g de noisettes.","Dégazer et ajouter les noix hachées et les 100g de raisins blonds.","Bien beurrer un moule à cake et y placer la pâte à brioche. Laisser au réfrigérateur pour une nuit.","Préchauffer le four à 150°C.","Cuire 7 minutes puis augmenter la température du four à 180°C et poursuivre la cuisson pendant 30 minutes.","Frotter la brioche chaude avec le morceau de beurre puis appliquer un mélange de sucre et de cannelle."]}]},
{title:"Moelleux au chocolat noir et au cœur fondant de praliné", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["200g de chocolat noir pâtissier","2 cuillères à soupe de lait","3 cuillères à soupe bombées de cacao amer en poudre","5 œufs","3 cuillères à soupe de farine","50g de sucre","50g de beurre","6 carrés de praliné en tablette"],
 steps:["Battre les 5 œufs avec les 50g de sucre.","Ajouter les 3 cuillères à soupe de farine et les 3 cuillères à soupe de cacao amer.","Faire fondre les 200g de chocolat noir avec les 2 cuillères à soupe de lait puis ajouter les 50g de beurre et le faire fondre en mélangeant.","Mélanger tous les ingrédients.","Laisser reposer la pâte.","Verser dans des moules individuels. Enfoncer un des 6 carrés de praliné dans chaque moule.","Cuire entre 10 et 12 minutes à 200°C."]}]},
{title:"Russe ou succès à la noisette", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:120, source:"", notes:"Les 140g de sucre blanc de la dacquoise ne sont pas explicitement rattachés à une étape dans la recette d'origine — traditionnellement on l'incorpore en pluie pendant que les blancs montent, pour serrer la meringue ; c'est le choix fait ici.", labels:[],
 parts:[
  {name:"Praliné", ingredients:["110g de sucre","30g d'eau","100g de noisettes","100g d'amandes","2g de fleur de sel"], steps:["Étaler les 100g de noisettes et 100g d'amandes sur une plaque à pâtisserie et les torréfier 30 à 40 minutes à 140°C.","Verser les 110g de sucre et les 30g d'eau dans une casserole, porter à feu vif. Lorsque des petites bulles apparaissent (121°C), ajouter les fruits secs : le sucre sable. Poursuivre la cuisson à feu moyen jusqu'à caramélisation. Couler sur une plaque et laisser refroidir avant de casser en morceaux et de mixer par impulsions au robot lame jusqu'à obtention d'un praliné lisse et coulant. Ajouter les 2g de fleur de sel."]},
  {name:"Dacquoise à la noisette", ingredients:["5 blancs d'œuf (150g)","1 pincée de sel","140g de sucre blanc","100g de poudre de noisettes","55g de poudre d'amandes","130g de sucre glace","20g de farine"], steps:["Préchauffer le four à 170°C chaleur tournante.","Mélanger les 100g de poudre de noisettes, 55g de poudre d'amandes, les 130g de sucre glace et les 20g de farine.","Dans le bol du robot, verser les 150g de blancs d'œufs et la pincée de sel et monter à vitesse moyenne, en incorporant les 140g de sucre blanc en pluie. Incorporer délicatement les poudres à la maryse.","Pocher sur papier cuisson en une plaque de 25x35cm.","Faire cuire pendant 20 à 22 minutes jusqu'à légère coloration dorée."]},
  {name:"Mousseline à la noisette", ingredients:["3 à 4 jaunes d'œuf (60g)","30g de fécule de maïs","280ml de lait entier","200g de praliné","170g de beurre"], steps:["Tiédir les 280ml de lait entier.","Mélanger les 60g de jaunes d'œufs et les 30g de fécule de maïs, détendre avec un quart du lait tiède puis reverser dans la casserole. Fouetter jusqu'à ébullition : c'est cuit quand la crème redevient fluide.","Débarrasser et mélanger pendant le refroidissement.","Incorporer la moitié des 170g de beurre en dés, émulsionner.","Étaler dans un plat froid et réfrigérer jusqu'à obtenir une température de 15°C.","Crémer le reste du beurre.","Lisser la pâtissière au batteur et incorporer le beurre crémé par cuillerées.","Ajouter les 200g de praliné préparé précédemment."]},
  {name:"Assemblage", ingredients:[], steps:["Tailler 2 rectangles identiques de biscuit.","Sur la première plaque, pocher une couche régulière de mousseline et recouvrir de la deuxième plaque de biscuit.","Réserver au moins 2 heures au réfrigérateur."]}
 ]},
{title:"Soda bread", category:"Boulangerie", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:50, restMin:0, source:"", notes:"", labels:[],
 parts:[{name:"", ingredients:["450g de farine complète","50g de flocons d'avoine","1 cuillère à café de sel","1 cuillère à soupe de bicarbonate de soude","2 cuillères à soupe de miel","450ml de lait ribot"],
 steps:["Préchauffer le four à 200°C.","Mélanger les 450g de farine complète, les 50g de flocons d'avoine, la cuillère à café de sel, la cuillère à soupe de bicarbonate de soude, les 2 cuillères à soupe de miel et les 450ml de lait ribot, et verser le mélange dans un moule à cake.","Cuire pendant 50 minutes."]}]},
{title:"Vacherin", category:"Dessert", difficulty:"", servingsBase:0, servingsUnit:"", prepMin:0, cookMin:0, restMin:240, source:"", notes:"Ne pas laisser plus de 3 jours au congélateur.", labels:[],
 parts:[{name:"", ingredients:["3 œufs","200g de crème fraîche épaisse d'Isigny","50g de sucre glace","100g de meringue"],
 steps:["Battre les jaunes des 3 œufs avec les 50g de sucre glace, ajouter les 200g de crème fraîche épaisse.","Battre les blancs en neige et ajouter au mélange précédent.","Ajouter les 100g de meringue en morceaux.","Faire prendre au congélateur pendant au moins 4 heures. Ne pas laisser plus de 3 jours."]}]}
];
